#!/usr/bin/env python3
"""
Extracts the GameTracker::eStep enum from GameStatus.hpp
and generates Client/Src/constants/steps.js by assigning
sequential numeric values (as the C++ compiler does).

Usage: python generate_steps.py
"""

import re
import os
import sys
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────
ROOT       = Path(__file__).parent
HPP_FILE   = ROOT / "Server" / "Src" / "GameStatus.hpp"
OUT_FILE   = ROOT / "Client" / "Src" / "constants" / "steps.js"

# ── Reading the source file ─────────────────────────────────────────────────
if not HPP_FILE.exists():
    print(f"[ERREUR] Fichier introuvable : {HPP_FILE}", file=sys.stderr)
    sys.exit(1)

hpp = HPP_FILE.read_text(encoding="utf-8")

# ── Extracting the eStep enum block ─────────────────────────────────────────
# Look for "enum eStep" then capture everything between { and }
match = re.search(r'enum\s+eStep\s*\{([^}]+)\}', hpp, re.DOTALL)
if not match:
    print("[ERREUR] enum eStep introuvable dans le fichier .hpp", file=sys.stderr)
    sys.exit(1)

enum_body = match.group(1)

# ── Parsing enum entries ────────────────────────────────────────────────────
# Supports: "name," / "name = value," / comments // and /* */
# First remove block comments /* … */
enum_body = re.sub(r'/\*.*?\*/', '', enum_body, flags=re.DOTALL)

entries = []
current_value = 0

for line in enum_body.splitlines():
    # Remove end-of-line comments
    line = re.sub(r'//.*', '', line).strip().rstrip(',').strip()
    if not line:
        continue

    # Peut contenir "name = explicit_value"
    if '=' in line:
        name, val_str = [p.strip() for p in line.split('=', 1)]
        # Integer literal values only (expressions are not handled)
        try:
            current_value = int(val_str, 0)
        except ValueError:
            print(f"[AVERTISSEMENT] Valeur non-littérale ignorée pour '{name}': {val_str}")
    else:
        name = line

    if re.match(r'^[A-Za-z_]\w*$', name):
        entries.append((name, current_value))
        current_value += 1

if not entries:
    print("[ERREUR] Aucune entrée extraite de l'enum.", file=sys.stderr)
    sys.exit(1)

# ── Generating the JS file ──────────────────────────────────────────────────
max_name_len = max(len(name) for name, _ in entries)

lines = []
lines.append("// !! AUTO-GENERATED FILE — DO NOT EDIT !!")
lines.append("// Generated by generate_steps.py from Server/Src/GameStatus.hpp")
lines.append("//")
lines.append("// To regenerate: python generate_steps.py")
lines.append("")
lines.append("/**")
lines.append(" * Numeric IDs of GameTracker::eStep (sequential C++ enum starting from 0).")
lines.append(" */")
lines.append("export const STEPS = {")

for name, value in entries:
    padding = ' ' * (max_name_len - len(name))
    lines.append(f"  {name}:{padding} {value},")

lines.append("}")
lines.append("")

OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
OUT_FILE.write_text('\n'.join(lines), encoding="utf-8")

print(f"[OK] {len(entries)} entrees extraites -> {OUT_FILE}")
