// !! AUTO-GENERATED FILE — DO NOT EDIT !!
// Generated by generate_steps.py from Server/Src/GameStatus.hpp
//
// To regenerate: python generate_steps.py

/**
 * Numeric IDs of GameTracker::eStep (sequential C++ enum starting from 0).
 */
export const STEPS = {
  waiting_room:                  0,
  start_game:                    1,
  quit_game:                     2,
  start_turn:                    3,
  director_selection:            4,
  director_election_begin:       5,
  vote_collection:               6,
  vote_result:                   7,
  vote_voldemort_elected:        8,
  vote_result_nox:               9,
  vote_result_lumos:             10,
  minister_draw:                 11,
  minister_discard:              12,
  director_veto:                 13,
  director_discard:              14,
  minister_veto_response:        15,
  veto_accepted:                 16,
  election_tracker_incremented:  17,
  ministry_enter_chaos:          18,
  law_on_top_of_the_pile_voted:  19,
  everyone_can_be_next_director: 20,
  law_voted:                     21,
  trigger_power_avada_kedavra:   22,
  player_to_kill_selection:      23,
  player_killed:                 24,
  voldemort_assassinated:        25,
  trigger_power_endoloris:       26,
  spying_player_selection:       27,
  player_spying:                 28,
  trigger_power_divination:      29,
  minister_check_top_cards:      30,
  trigger_power_impero:          31,
  next_minister_selection:       32,
  next_minister_selected:        33,
  end_of_turn:                   34,
  game_finished:                 35,
}
